= Analyze Twitter Feeds using N1QL

== Configure Twitter Credentials

. Create a new app: https://apps.twitter.com/app/new
. TODO

== Run Application using CLI

. Get home timeline of pre-defined user: `mvn package exec:java`
. Get home timeline a specific user: `mvn package exec:java -Dtwitter.user=arungupta`

== Setup Couchbase

. Setup Couchbase as explained at https://github.com/couchbase-guides/couchbase-amazon-cli
. Create a bucket `twitter`
. Create primary index `create primary index on twitter;`
. Create secondary index `create index twitter_created_at on twitter(createdAt);`

== Deploy Lambda

. Create package: `mvn package`
. Upload JAR to S3: `aws s3 cp target/twitter-feed-1.0-SNAPSHOT.jar s3://arungupta.me/twitter-feed-1.0-SNAPSHOT.jar`
. Deploy Lambda:
+
```
aws cloudformation deploy \
--template-file template.yml \
--stack-name twitter \
--region us-west-2
```
+
. Delete the stack (if an stack needs to be updated):
+
```
aws cloudformation delete-stack \
--stack-name twitter \
--region us-west-2
```

== Configure Database Backup

. Login to host: `ssh -i ~/.ssh/arun-cb-west2.pem ubuntu@<public-ip>`
. Configure `s3cmd`
.. Import S3tools signing key: `wget -O- -q http://s3tools.org/repo/deb-all/stable/s3tools.key | sudo apt-key add -`
.. Add the repo to `sources.list`: `sudo wget -O/etc/apt/sources.list.d/s3tools.list http://s3tools.org/repo/deb-all/stable/s3tools.list`
.. Refresh package cache and install the newest s3cmd: `sudo apt-get update && sudo apt-get install s3cmd`
.. Configure s3cmd: `s3cmd --configure`
+
```
New settings:
  Access Key: <access key>
  Secret Key: <secret key>
  Encryption password: <password>
  Path to GPG program: /usr/bin/gpg
  Use HTTPS protocol: False
  HTTP Proxy server name: 
  HTTP Proxy server port: 0
```
+
. Backup
.. Make backup directory: `sudo mkdir /opt/couchbase/backup`
.. Change perms: `sudo chmod 777 /opt/couchbase/backup`
.. Backup: `/opt/couchbase/bin/cbbackup http://localhost:8091 ./backup -u Administrator -p password`
. Upload to S3: `s3cmd --recursive put ./backup/2017-01-09T141646Z s3://arungupta.me/twitter-feed.backup/`
+
```
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
./backup/2017-01-09T141646Z/2017-01-09T141646Z-full/bucket-twitter/index.json -> s3://arungupta.me/twitter-feed.backup/2017-01-09T141646Z/2017-01-09T141646Z-full/bucket-twitter/index.json  [1 of 6]
 1208 of 1208   100% in    0s    28.00 kB/s  done
./backup/2017-01-09T141646Z/2017-01-09T141646Z-full/bucket-twitter/node-127.0.0.1%3A8091/data-0000.cbb -> s3://arungupta.me/twitter-feed.backup/2017-01-09T141646Z/2017-01-09T141646Z-full/bucket-twitter/node-127.0.0.1%3A8091/data-0000.cbb  [2 of 6]
 530432 of 530432   100% in    0s    11.16 MB/s  done
./backup/2017-01-09T141646Z/2017-01-09T141646Z-full/bucket-twitter/node-127.0.0.1%3A8091/failover.json -> s3://arungupta.me/twitter-feed.backup/2017-01-09T141646Z/2017-01-09T141646Z-full/bucket-twitter/node-127.0.0.1%3A8091/failover.json  [3 of 6]
 31202 of 31202   100% in    0s   983.59 kB/s  done
./backup/2017-01-09T141646Z/2017-01-09T141646Z-full/bucket-twitter/node-127.0.0.1%3A8091/meta.json -> s3://arungupta.me/twitter-feed.backup/2017-01-09T141646Z/2017-01-09T141646Z-full/bucket-twitter/node-127.0.0.1%3A8091/meta.json  [4 of 6]
 12 of 12   100% in    0s   126.95 B/s  done
./backup/2017-01-09T141646Z/2017-01-09T141646Z-full/bucket-twitter/node-127.0.0.1%3A8091/seqno.json -> s3://arungupta.me/twitter-feed.backup/2017-01-09T141646Z/2017-01-09T141646Z-full/bucket-twitter/node-127.0.0.1%3A8091/seqno.json  [5 of 6]
 1042 of 1042   100% in    0s    20.50 kB/s  done
./backup/2017-01-09T141646Z/2017-01-09T141646Z-full/bucket-twitter/node-127.0.0.1%3A8091/snapshot_markers.json -> s3://arungupta.me/twitter-feed.backup/2017-01-09T141646Z/2017-01-09T141646Z-full/bucket-twitter/node-127.0.0.1%3A8091/snapshot_markers.json  [6 of 6]
 1567 of 1567   100% in    0s     7.44 kB/s  done
```

== Queries

. Number of tweets stored
+
.Query
[source, text]
----
select count(*) from twitter;
----
+
.Result
[source, json]
----
[
  {
    "$1": 203
  }
]
----
+
. One tweet
+
.Query
[source, text]
----
select * from twitter LIMIT 1;
----
+
.Result
[source, json]
----
[
  {
    "twitter": {
      "accessLevel": "0",
      "contributors": [],
      "createdAt": "1480828438000",
      "currentUserRetweetId": "-1",
      "displayTextRangeEnd": "-1",
      "displayTextRangeStart": "-1",
      "favoriteCount": "116356",
      "favorited": false,
      "geoLocation": null,
      "hashtagEntities": [],
      "id": "805278955150471168",
      "inReplyToScreenName": null,
      "inReplyToStatusId": "-1",
      "inReplyToUserId": "-1",
      "lang": "en",
      "mediaEntities": [],
      "place": null,
      "possiblySensitive": false,
      "quotedStatus": null,
      "quotedStatusId": "-1",
      "rateLimitStatus": null,
      "retweet": false,
      "retweetCount": "28330",
      "retweeted": false,
      "retweetedByMe": false,
      "retweetedStatus": null,
      "scopes": null,
      "source": "<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>",
      "symbolEntities": [],
      "text": "Just tried watching Saturday Night Live - unwatchable! Totally biased, not funny and the Baldwin impersonation just can't get any worse. Sad",
      "truncated": false,
      "urlentities": [],
      "user": {
        "accessLevel": "0",
        "biggerProfileImageURL": "http://pbs.twimg.com/profile_images/1980294624/DJT_Headshot_V2_bigger.jpg",
        "biggerProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1980294624/DJT_Headshot_V2_bigger.jpg",
        "contributorsEnabled": false,
        "createdAt": "1237383998000",
        "defaultProfile": false,
        "defaultProfileImage": false,
        "description": "President-elect of the United States",
        "descriptionURLEntities": [],
        "email": null,
        "favouritesCount": "46",
        "followRequestSent": false,
        "followersCount": "19294404",
        "friendsCount": "42",
        "geoEnabled": true,
        "id": "25073877",
        "lang": "en",
        "listedCount": "52499",
        "location": "New York, NY",
        "miniProfileImageURL": "http://pbs.twimg.com/profile_images/1980294624/DJT_Headshot_V2_mini.jpg",
        "miniProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1980294624/DJT_Headshot_V2_mini.jpg",
        "name": "Donald J. Trump",
        "originalProfileImageURL": "http://pbs.twimg.com/profile_images/1980294624/DJT_Headshot_V2.jpg",
        "originalProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1980294624/DJT_Headshot_V2.jpg",
        "profileBackgroundColor": "6D5C18",
        "profileBackgroundImageURL": "http://pbs.twimg.com/profile_background_images/530021613/trump_scotland__43_of_70_cc.jpg",
        "profileBackgroundImageUrlHttps": "https://pbs.twimg.com/profile_background_images/530021613/trump_scotland__43_of_70_cc.jpg",
        "profileBackgroundTiled": true,
        "profileBannerIPadRetinaURL": "https://pbs.twimg.com/profile_banners/25073877/1479776952/ipad_retina",
        "profileBannerIPadURL": "https://pbs.twimg.com/profile_banners/25073877/1479776952/ipad",
        "profileBannerMobileRetinaURL": "https://pbs.twimg.com/profile_banners/25073877/1479776952/mobile_retina",
        "profileBannerMobileURL": "https://pbs.twimg.com/profile_banners/25073877/1479776952/mobile",
        "profileBannerRetinaURL": "https://pbs.twimg.com/profile_banners/25073877/1479776952/web_retina",
        "profileBannerURL": "https://pbs.twimg.com/profile_banners/25073877/1479776952/web",
        "profileImageURL": "http://pbs.twimg.com/profile_images/1980294624/DJT_Headshot_V2_normal.jpg",
        "profileImageURLHttps": "https://pbs.twimg.com/profile_images/1980294624/DJT_Headshot_V2_normal.jpg",
        "profileLinkColor": "0D5B73",
        "profileSidebarBorderColor": "BDDCAD",
        "profileSidebarFillColor": "C5CEC0",
        "profileTextColor": "333333",
        "profileUseBackgroundImage": true,
        "protected": false,
        "rateLimitStatus": null,
        "screenName": "realDonaldTrump",
        "showAllInlineMedia": false,
        "status": null,
        "statusesCount": "34269",
        "timeZone": "Eastern Time (US & Canada)",
        "translator": false,
        "url": "https://t.co/mZB2hymxC9",
        "urlentity": {
          "displayURL": "https://t.co/mZB2hymxC9",
          "end": "23",
          "expandedURL": "https://t.co/mZB2hymxC9",
          "start": "0",
          "text": "https://t.co/mZB2hymxC9",
          "url": "https://t.co/mZB2hymxC9"
        },
        "utcOffset": "-18000",
        "verified": true,
        "withheldInCountries": null
      },
      "userMentionEntities": [],
      "withheldInCountries": null
    }
  }
]
----
+
. Top 5 tweeting days
+
.Query
[source, text]
----
SELECT SUBSTR(millis_to_str(to_num(createdAt)), 0, 10) tweet_date, 
       COUNT(1) tweet_count
FROM   twitter 
GROUP  BY SUBSTR(millis_to_str(to_num(createdAt)), 0, 10) 
ORDER  BY COUNT(1) DESC 
LIMIT  5;
----
+
.Result
[source, json]
----
[
  {
    "tweet_count": 12,
    "tweet_date": "2017-01-06"
  },
  {
    "tweet_count": 11,
    "tweet_date": "2016-12-04"
  },
  {
    "tweet_count": 10,
    "tweet_date": "2017-01-03"
  },
  {
    "tweet_count": 10,
    "tweet_date": "2017-01-04"
  },
  {
    "tweet_count": 9,
    "tweet_date": "2016-12-10"
  }
]
----
+
. Most common hour in a day to tweet
+
.Query
[source, text]
----
SELECT SUBSTR(millis_to_str(to_num(createdAt)), 11, 2) tweet_hour, 
       COUNT(1) tweet_count
FROM   twitter 
GROUP  BY SUBSTR(millis_to_str(to_num(createdAt)), 11, 2) 
ORDER  BY tweet_count DESC 
LIMIT  5;
----
+
.Result
[source, json]
----
[
  {
    "tweet_count": 33,
    "tweet_hour": "13"
  },
  {
    "tweet_count": 25,
    "tweet_hour": "11"
  },
  {
    "tweet_count": 24,
    "tweet_hour": "12"
  },
  {
    "tweet_count": 15,
    "tweet_hour": "14"
  },
  {
    "tweet_count": 14,
    "tweet_hour": "00"
  }
]
----
+
. Most common day of the week to tweet
+
.Query
[source, text]
----
SELECT date_part_str(millis_to_str(to_num(createdAt)), "day_of_week") day_of_week, 
       COUNT(1) tweet_count
FROM   twitter 
GROUP  BY date_part_str(millis_to_str(to_num(createdAt)), "day_of_week")
ORDER  BY tweet_count DESC 
LIMIT  5;
----
+
.Result
[source, json]
----
[
  {
    "day_of_week": 0,
    "tweet_count": 40
  },
  {
    "day_of_week": 5,
    "tweet_count": 36
  },
  {
    "day_of_week": 2,
    "tweet_count": 36
  },
  {
    "day_of_week": 6,
    "tweet_count": 33
  },
  {
    "day_of_week": 1,
    "tweet_count": 33
  }
]
----
+
RFE: Given a date, return the English name for it
+
. Top 3 mentions in tweets
+
.Query
[source, text]
----
select count(1) user_count, ue.screenName 
    from twitter 
    UNNEST userMentionEntities ue 
    GROUP by ue.screenName 
    ORDER by user_count DESC
    LIMIT 5;
----
+
.Result
[source, json]
----
[
  {
    "screenName": "realDonaldTrump",
    "user_count": 8
  },
  {
    "screenName": "FoxNews",
    "user_count": 7
  },
  {
    "screenName": "CNN",
    "user_count": 5
  },
  {
    "screenName": "DanScavino",
    "user_count": 5
  },
  {
    "screenName": "mike_pence",
    "user_count": 4
  }
]
----
+
TODO: Talk about `user_count` vs `User_count` based upon which field should be shown first.
+
. Top 3 tweets with RTs
+
.Query
[source, text]
----
select retweetCount, text
from twitter
order by retweetCount
limit 5;
----
+
.Result
[source, json]
----
[
  {
    "retweetCount": "10140",
    "text": "Thank you to all of the men and women who protect & serve our communities 24/7/365! \n#LawEnforcementAppreciationDay… https://t.co/aqUbDipSgv"
  },
  {
    "retweetCount": "10370",
    "text": "We had a great News Conference at Trump Tower today. A couple of FAKE NEWS organizations were there but the people truly get what's going on"
  },
  {
    "retweetCount": "10414",
    "text": "these companies are able to move between all 50 states, with no tax or tariff being charged. Please be forewarned prior to making a very ..."
  },
  {
    "retweetCount": "10416",
    "text": "Somebody hacked the DNC but why did they not have \"hacking defense\" like the RNC has and why have they not responded to the terrible......"
  },
  {
    "retweetCount": "10428",
    "text": "The resolution being considered at the United Nations Security Council regarding Israel should be vetoed....cont: https://t.co/s8rXKKZNF1"
  }
]
----
+
. Original tweets vs RTs
+
.Query
[source, text]
----
select retweet, count(1) count from twitter
group by retweet;
----
+
.Result
[source, json]
----
[
  {
    "count": 13,
    "retweet": true
  },
  {
    "count": 225,
    "retweet": false
  }
]
----
+
. Most common words
+
.Query
[source, text]
----
select count(1) count, word 
FROM twitter 
UNNEST split(text) word
GROUP by word
ORDER BY count DESC;
----
+
.Result
[source, json]
----
[
  {
    "count": 168,
    "word": "the"
  },
  {
    "count": 134,
    "word": "to"
  },
  {
    "count": 100,
    "word": "and"
  },

  . . .

  {
    "count": 1,
    "word": "Pres-Elect"
  },
  {
    "count": 1,
    "word": "dealing"
  },
  {
    "count": 1,
    "word": "asking"
  }
]  
----
+
. How many times the following words are mentioned? A, B, C
+
.Query
[source, text]
----
select count(1) count, lower(w) 
from twitter  
unnest split(text) w  
WHERE lower(w) IN [ "media", "fake", "america"] 
GROUP by lower(w) 
ORDER BY count DESC;
----
+
.Result
[source, json]
----
[
  {
    "$1": "media",
    "count": 11
  },
  {
    "$1": "fake",
    "count": 8
  },
  {
    "$1": "america",
    "count": 7
  }
]
----
+

TODO: All reserved words are CAPITAL

